export const commonPatterns = [
  {
    id: 'email',
    label: 'Email',
    tone: 0,
    pattern: '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}',
    flags: 'gi',
    sample: 'dev@example.com\nsales@example.co.uk\nnot-an-email',
  },
  {
    id: 'url',
    label: 'URL',
    tone: 1,
    pattern: 'https?:\\/\\/[^\\s]+',
    flags: 'gi',
    sample: 'Docs: https://example.com/docs?id=1\nLocal: http://localhost:5173',
  },
  {
    id: 'ipv4',
    label: 'IPv4',
    tone: 2,
    pattern: '\\b(?:25[0-5]|2[0-4]\\d|1?\\d?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|1?\\d?\\d)){3}\\b',
    flags: 'g',
    sample: 'Gateway 192.168.0.1\nInvalid 999.1.1.1\nDNS 8.8.8.8',
  },
  {
    id: 'uuid',
    label: 'UUID',
    tone: 3,
    pattern: '\\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\\b',
    flags: 'gi',
    sample: '019c6e27-e55b-73d1-87d8-4e01f1f75043\nnot-a-uuid',
  },
  {
    id: 'hex-color',
    label: 'HEX color',
    tone: 4,
    pattern: '#(?:[0-9a-fA-F]{3}){1,2}\\b',
    flags: 'g',
    sample: '#fff\n#2F6F73\n#badhexg',
  },
  {
    id: 'iso-date',
    label: 'ISO date',
    tone: 5,
    pattern: '\\b\\d{4}-\\d{2}-\\d{2}(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3})?)?(?:Z|[+-][0-2]\\d:?[0-5]\\d)?)?\\b',
    flags: 'g',
    sample: '2026-07-01\n2026-07-01T15:30:00Z\n07/01/2026',
  },
  {
    id: 'time',
    label: 'Time',
    tone: 6,
    pattern: '\\b(?:[01]?\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d)?\\b',
    flags: 'g',
    sample: '09:30\n23:59:58\n25:00',
  },
  {
    id: 'number',
    label: 'Number',
    tone: 7,
    pattern: '[-+]?\\d*\\.?\\d+(?:[eE][-+]?\\d+)?',
    flags: 'g',
    sample: '42\n-3.14\n1.2e-5\nabc',
  },
  {
    id: 'quoted',
    label: 'Quoted string',
    tone: 8,
    pattern: `(["'])(?:(?=(\\\\?))\\2.)*?\\1`,
    flags: 'g',
    sample: `"hello world"\n'single quoted'\nplain text`,
  },
  {
    id: 'html-tag',
    label: 'HTML tag',
    tone: 9,
    pattern: '<\\/?[A-Za-z][^>]*>',
    flags: 'g',
    sample: '<div class="box">Text</div>\nplain text',
  },
  {
    id: 'cjk',
    label: 'CJK characters',
    tone: 10,
    pattern: '[\\u4E00-\\u9FFF]+',
    flags: 'g',
    sample: 'English 中文 日本語 한국어',
  },
] as const;

export type RegexPatternPreset = (typeof commonPatterns)[number];
